<?php

/**
* @file
* Recipe Gallery Admin module.
*
*/

/**
* Implements hook_block_info().
*
* Define all blocks provided by the module.
*/
function recipe_gallery_admin_block_info() {
  //Define an associative array for each block, in this case just one:
  $blocks['add_recipe_content'] = array(
    'info' => t('Add Recipe Content'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    );

  return $blocks;
}

/**
* Implements hook_block_view().
*
* Return a rendered or renderable view of a block.
*/

function recipe_gallery_admin_block_view($delta = '') {
  $block = array();

  switch ($delta) {
     case 'add_recipe_content':
      //The default localized title of the block which is NULL
      $block['subject'] = NULL;

      // The content of the block's body.
      $block['content'] = recipe_gallery_admin_contents($delta);
       break;
   }
   return $block;
}

/**
* Function that generates the content for d7dev_admin blocks.
*/

function recipe_gallery_admin_contents($delta = '') {
  //additional blocks may be added, so base this on the block $delta
  switch ($delta) {
    case 'add_recipe_content':
      //just a simple render array with a link
      $add_recipe_link = array(
        '#theme' => 'link',
        '#text' => t('Add New Recipe'),
        '#path' => 'node/add/recipe',
        '#options' => array(
          'attributes' => array(),
          //Required:
          'html' => FALSE,
        ),
      );
      return $add_recipe_link;
  }
}

/**
* Implementation of hook_wysiwyg_editor_settings_alter().
*/

function recipe_gallery_admin_wysiwyg_editor_settings_alter(&$settings, &$context) {
  if($context['profile']->editor == 'ckeditor' || $context['profile']->editor == 'nicedit') {
    $settings['forcePasteAsPlainText'] = TRUE;
  }
}


?>
